#
# Hardware settings for a general VM.
# Works on QEMU Virt-Manager and Virtualbox
#
# flake.nix
#  └─ ./hosts
#      └─ ./vm
#          └─ hardware-configuration.nix *
#
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#

{ config, lib, pkgs, profile, u, vmid, hostname, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot = {
    # loader.grub = {
    #   enable = true;
    #   devices = ["/dev/vda"];
    # };
    
    initrd = {
      availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" "virtio_blk" ];
      kernelModules = [ ];
    };
    extraModulePackages = [ ];
  };

  # zfs
  # boot.supportedFilesystems = [ "zfs" ];
  # services.zfs = {
  #   autoScrub.enable = true;
  #   trim.enable = true;
  # };


  # fileSystems."/" =
  #   { device = "/dev/disk/by-uuid/7e38979e-68c7-466c-b8b7-db7b979841cd";
  #     fsType = "ext4";
  #   };

  # fileSystems."/home" =
  #   { device = "/dev/disk/by-uuid/09ad8c4c-f140-494b-9277-37f46ab0c157";
  #     fsType = "xfs";
  #   };
  # # fileSystems."/var/lib/docker" =
  # #   { device = "/dev/disk/by-uuid/049a8269-2f23-48d1-8381-38db88c0459b";
  # #     fsType = "ext4";
  # #   };
  # fileSystems."/mnt/cache" =
  #   { device = "/dev/disk/by-uuid/6e7e9cce-524d-41cc-8507-e1e8a57f4de4";
  #     fsType = "ext4";
  #   };
  # fileSystems."/media/pvenfs" = {
  #   device = "nfs.l.nervasion.com:/mnt/nas/orya";
  #   fsType = "nfs";
  #   options = [ "x-systemd.automount" "noauto" ];
  # };



  swapDevices = [ ];


  # services.resolved = {
  #   enable = true;
  #   #dnssec = "true";
  #   domains = [ "~." ];
  #   fallbackDns = [ "10.28.1.1" ];
  #   #dnsovertls = "true";
  # };


  systemd.network = {
    enable = true;
    networks = {
      "10-ens18" = {
        # match the interface by name
        matchConfig.Name = "ens18";
        address = [
          # configure addresses including subnet mask
          (profile.ip + "/16")
        ];
        routes = [
          { Gateway = "10.28.1.1"; }
        ];
        dns = ["10.28.1.1" "1.1.1.1"];
        # make the routes on this interface a dependency for network-online.target
        linkConfig.RequiredForOnline = "routable";
      };
    };
  };
  networking = {
      hostName = u.getOrDefault profile "networking.hostName" "nixos";
      useDHCP = false; # Deprecated
      useNetworkd = true;
  };
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  #hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  #virtualisation.virtualbox.guest.enable = true;     #currently disabled because package is broken
  #powerManagement.cpuFreqGovernor = "performance"
}
