# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, t2-firmware, system, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.kernelParams = [ "intel_iommu=on" "iommu=pt" "pcie_ports=compat" ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "brcmfmac" ];
  boot.blacklistedKernelModules = [ "b43" "wl" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.extraModprobeConfig = ''
  options brcmfmac feature_disable=0x01
  options brcmfmac feature_disable=0x82000
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c2a65de8-8482-4fe9-b3c4-b1aba9767f90";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5F66-17ED";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking = {
  #   interfaces = {
  #     enp124s0u1c2 = {
  #       ipv4.addresses = [
  #         {
  #           address = "192.168.64.88";
  #           prefixLength = 24;      
  #         }
  #       ];        
  #     };
  #   };
  #   defaultGateway = "192.168.64.255";
  #   nameservers = [
  #     "1.1.1.1" 
  #   ];
  #   hostName = "pmp-cape";
  # };
  
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp124s0u2u2u4.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.firmware = [
    t2-firmware.packages.${system}.brcm
  ];
}
